//import Vue from 'vue';
import breakpoints from './components/breakpoints';
import sliders from './components/sliders';
import gumburger from './components/gumburger';
import popups from './components/popups';
import validate from './components/validate';
import subscribe from './components/subscribe';
import accordion from './components/accordion';
import textTable from './components/text-table';
import fullscreenMenu from './components/fullscreen-menu';
import mainMenu from './components/main-menu';
import flexMenu from './components/flex-menu';
import tabsComp from './components/tabs';
import tabsSelectComp from './components/tabs-select';
import mobileTable from './components/mobileTable';
import signUp from './components/sign-up';
import mask from './components/mask';
import datepickers from './components/datepickers';
import svg4everybody from './components/svg4everybody';
import pageReload from './components/page-reload';
import payTabs from './components/pay-tabs';
import calcItogo from './components/calc-itogo';
import menuSelect from './components/menu-select';
//import basket from './components/basket';
import message from './components/message';
import selectOpenNewTab from './components/select-open-new-tab';
import shadowCard from './components/shadow-card';
import addNewCode from './components/add-new-code';
import forms from './components/forms'
import formOrderChangeStatus from './components/form-order-change-status';
import formOrderChangeStatusInList from './components/form-order-change-status-in-list';
import formUsligaChangeStatus from './components/form-usluga-сhange-status';
import formUsligaChangeStatusInList from './components/form-usluga-change-status-in-list';
import formUsligaAssignMoA from './components/form-usluga-assign-master-or-agent';
import formAddMemberMoA from './components/form-add-member-master-or-agent';
import formMobileChange from './components/form-mobile-change';
import formFeedback from './components/form-feedback';
import lastOrdersToggle from './components/last-orders-toggle';
import lastOrdersCategory from './components/last-orders-category';
import toddler from './components/toddler';
import ensurance from './components/ensurance';
import addLcData from './components/add-lc-data';
import psevdoTable from './components/psevdo-table';
import uslugi from './components/uslugi';
import sticky from './components/sticky';
import kladr from './components/kladr';
import results from './components/results';
import fancy from './components/fancy';


$(function(){
	breakpoints();
	sliders();
	gumburger();
	popups();
	mask();
	validate();
	subscribe();
	accordion();
	textTable();
	fullscreenMenu();
	mainMenu();
	flexMenu();
	tabsComp();
	tabsSelectComp();
	mobileTable();
	signUp();
	datepickers();
	svg4everybody();
	pageReload();
	payTabs();
	calcItogo();
	menuSelect();
	//basket();
	message();
	forms();
	selectOpenNewTab();
    shadowCard();
    addNewCode();
    formOrderChangeStatus();
    formOrderChangeStatusInList();
    formUsligaChangeStatus();
    formUsligaChangeStatusInList();
    formUsligaAssignMoA();
    formAddMemberMoA();
    formMobileChange();
    formFeedback();
    lastOrdersToggle();
    lastOrdersCategory();
    toddler();
    ensurance();
    addLcData();
    psevdoTable();
    uslugi();
    sticky();
    kladr();
    results();
    fancy();
});


